# Site settings
title: Yousry Mohamed
description: 'Yousry Mohamed Blog'
url: 'http://ylashin.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Yousry Mohamed'
  email: Yousry Mohamed@readify.net
  twitter_username: to-be-provided
  facebook_username: to-be-provided
  github_username:  to-be-provided
  linkedin_username:  to-be-provided

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
